on:
  repository_dispatch:
  schedule:
    - cron: '01 0 * * *'
name: Update
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Update npm
        run: |
          npm install -g npm
          npm --version
      - name: Install dependencies
        run: npm ci
      - name: npm ls
        run: npm ls
      - name: Pull logs
        run: |
          mkdir -p logs/
          npm run pull -- $(date -uI --date='-31 days') $(date -uI --date='-1 days') -o logs/
      - name: pisg
        run: |
          mkdir -p cache/ out/
          perl ./pisg/pisg logs/
      - name: Minify HTML
        run: npm run minify
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
